# Generated by Django 5.1.5 on 2026-08-24 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammeColle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semaine', models.PositiveIntegerField()),
                ('programme', models.TextField()),
                ('matiere', models.CharField(choices=[('PH', 'Physique'), ('CH', 'Chimie'), ('MT', 'Maths'), ('AN', 'Anglais'), ('FR', 'Français')], max_length=2)),
            ],
        ),
    ]
