# Generated by Django 5.1.5 on 2025-03-04 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='colle',
            name='colleur',
            field=models.ForeignKey(limit_choices_to=models.Q(('colleur', None), _negated=True), on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='note',
            name='eleve',
            field=models.ForeignKey(limit_choices_to=models.Q(('colleur', None)), on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='GroupColle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.IntegerField()),
                ('numero', models.IntegerField()),
                ('eleves', models.ManyToManyField(limit_choices_to=models.Q(('colleur', None)), to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='colle',
            name='group',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='notes.groupcolle'),
            preserve_default=False,
        ),
    ]
