# Generated by Django 5.1.5 on 2025-03-04 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_colle_colleur_alter_note_eleve_groupcolle_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colle',
            old_name='group',
            new_name='groupColle',
        ),
    ]
