# Generated by Django 5.1.5 on 2025-03-05 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connexion', '0005_myuser_alter_colleur_user'),
        ('notes', '0003_rename_group_colle_groupcolle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colle',
            name='colleur',
            field=models.ForeignKey(limit_choices_to=models.Q(('colleur', None), _negated=True), on_delete=django.db.models.deletion.CASCADE, to='connexion.myuser'),
        ),
        migrations.AlterField(
            model_name='groupcolle',
            name='eleves',
            field=models.ManyToManyField(limit_choices_to=models.Q(('colleur', None)), to='connexion.myuser'),
        ),
        migrations.AlterField(
            model_name='note',
            name='eleve',
            field=models.ForeignKey(limit_choices_to=models.Q(('colleur', None)), on_delete=django.db.models.deletion.CASCADE, to='connexion.myuser'),
        ),
    ]
