# Generated by Django 5.1.5 on 2025-03-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_alter_colle_colleur_alter_groupcolle_eleves_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colle',
            name='matiere',
            field=models.CharField(choices=[('PH', 'Physique'), ('CH', 'Chimie'), ('MT', 'Maths'), ('AN', 'Anglais'), ('FR', 'Français')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
