# Generated by Django 5.1.5 on 2025-03-13 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_colle_matiere'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colle',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['colle']},
        ),
        migrations.AddField(
            model_name='colle',
            name='semestre',
            field=models.IntegerField(choices=[(1, 1), (2, 2)], default=1),
            preserve_default=False,
        ),
    ]
