# Generated by Django 5.1.5 on 2025-03-13 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_alter_colle_options_alter_note_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colle',
            name='semestre',
        ),
        migrations.AlterField(
            model_name='groupcolle',
            name='semestre',
            field=models.IntegerField(choices=[(1, 1), (2, 2)]),
        ),
    ]
