# Generated by Django 5.1.5 on 2025-03-13 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_remove_colle_semestre_alter_groupcolle_semestre'),
    ]

    operations = [
        migrations.AddField(
            model_name='colle',
            name='semestre',
            field=models.IntegerField(choices=[(1, 1), (2, 2)], default=1),
            preserve_default=False,
        ),
    ]
