# Generated by Django 5.1.5 on 2025-12-18 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_colle_semestre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colle',
            name='matiere',
        ),
    ]
