# Generated by Django 5.1.5 on 2025-12-18 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connexion', '0008_alter_colleur_matiere'),
        ('notes', '0009_remove_colle_matiere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colle',
            name='colleur',
            field=models.ForeignKey(limit_choices_to=models.Q(('colleur', None), _negated=True), on_delete=django.db.models.deletion.CASCADE, to='connexion.colleur'),
        ),
    ]
