# Generated by Django 5.1.5 on 2026-04-02 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0010_alter_colle_colleur'),
    ]

    operations = [
        migrations.AddField(
            model_name='colle',
            name='horaire',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='colle',
            name='salle',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AddField(
            model_name='colle',
            name='sujet',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
    ]
