# Generated by Django 5.1.5 on 2026-06-02 07:52

import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=30)),
                ('matiere', models.CharField(choices=[('PH', 'Physique'), ('CH', 'Chimie'), ('MT', 'Maths'), ('AN', 'Anglais'), ('FR', 'Français')], max_length=2)),
                ('fichier', models.FileField(upload_to=documents.models.dossierUtilisateur)),
            ],
        ),
    ]
