# Generated by Django 5.1.5 on 2026-06-04 11:36

import django.db.models.deletion
import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='nature',
            field=models.CharField(choices=[('TD', 'DS'), ('DS', 'DS'), ('CR', 'Cours'), ('DM', 'DM')], default='TD', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='titre',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Correction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50)),
                ('fichier', models.FileField(upload_to=documents.models.dossierUtilisateur)),
                ('fichierExo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='documents.document')),
            ],
        ),
    ]
