# Generated by Django 5.1.5 on 2026-08-24 08:11

import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_nature_alter_document_titre_correction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['titre']},
        ),
        migrations.AlterField(
            model_name='correction',
            name='fichier',
            field=models.FileField(upload_to=documents.models.dossierUtilisateurCorrection),
        ),
        migrations.AlterField(
            model_name='document',
            name='nature',
            field=models.CharField(choices=[('TD', 'TD'), ('DS', 'DS'), ('CR', 'Cours'), ('DM', 'DM'), ('CO', 'Correction')], max_length=2),
        ),
    ]
