# Generated by Django 5.1.5 on 2025-03-02 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connexion', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='colleur',
            name='matiere',
            field=models.CharField(choices=[('PH', 'physique'), ('CH', 'chimie'), ('MT', 'maths'), ('AN', 'anglais'), ('FR', 'français')], default='physique', max_length=2),
            preserve_default=False,
        ),
    ]
