# Generated by Django 5.1.5 on 2025-03-05 14:15

import django.contrib.auth.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('connexion', '0004_colleur_matiere'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='colleur',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='connexion.myuser'),
        ),
    ]
