# Generated by Django 5.1.5 on 2025-03-05 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connexion', '0005_myuser_alter_colleur_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colleur',
            old_name='user',
            new_name='myuser',
        ),
    ]
