# Generated by Django 5.1.5 on 2025-03-05 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connexion', '0006_rename_user_colleur_myuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colleur',
            old_name='myuser',
            new_name='user',
        ),
    ]
