# Generated by Django 5.1.5 on 2025-12-18 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connexion', '0007_rename_myuser_colleur_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colleur',
            name='matiere',
            field=models.CharField(choices=[('PH', 'Physique'), ('CH', 'Chimie'), ('MT', 'Maths'), ('AN', 'Anglais'), ('FR', 'Français')], max_length=2),
        ),
    ]
