# Generated by Django 5.1.5 on 2025-12-18 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connexion', '0008_alter_colleur_matiere'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colleur',
            old_name='user',
            new_name='colleur',
        ),
    ]
