# Generated by Django 5.1.5 on 2026-08-24 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connexion', '0009_rename_user_colleur_colleur'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'ordering': ['last_name', 'first_name']},
        ),
    ]
